server:
  port: 8800
spring:
  datasource:
    #连接数据库的url
    url: jdbc:mysql://localhost:3306/excel?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    #驱动
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: dawjxxx
mybatis-plus:
  type-aliases-package: com.xxx.module