server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dawjxxx
  
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        format_sql: true
    show-sql: true
    database: mysql
  application:
    name: jpa