server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: dawjxxx
#mybatis:
#  # 搜索指定包别名
#  typeAliasesPackage: com.xxx.entities
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath:mapper/*Mapper.xml
#  configuration:
#    map-underscore-to-camel-case: true
mybatis-plus:
  type-aliases-package: com.xxx.entities